# Generated by Django 5.0.7 on 2025-08-10 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0003_cartitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="fooditem",
            name="category",
            field=models.CharField(
                choices=[
                    ("meals", "Meals"),
                    ("pastries", "Pastries"),
                    ("groceries", "Groceries"),
                    ("drinks", "Drinks"),
                    ("snacks", "Snacks"),
                ],
                default="meals",
                max_length=20,
            ),
        ),
    ]
