# Generated by Django 5.0.7 on 2025-08-10 23:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0004_fooditem_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="store",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="store",
            index=models.Index(fields=["city"], name="listings_st_city_26d7b0_idx"),
        ),
        migrations.AddIndex(
            model_name="store",
            index=models.Index(
                fields=["latitude", "longitude"], name="listings_st_latitud_f31cd6_idx"
            ),
        ),
    ]
