# Generated by Django 5.2 on 2025-04-25 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accaunts", "0002_usertoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=255)),
                ("token", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="usertoken",
            name="token",
            field=models.CharField(max_length=255),
        ),
    ]
