# Generated by Django 5.2 on 2025-04-28 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accaunts", "0003_reset_alter_usertoken_token"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
