# Generated by Django 5.0.7 on 2025-08-04 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accaunts", "0004_alter_user_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="last name"
            ),
        ),
    ]
